### ISSUE TITLE
All built-in renderers always return [object Object]

### ISSUE THREAD

**Issue by sbelak** [JonyEpsilon/gorilla-repl#219] opened 2015-06-18 08:28 UTC
Both plots and simple expressions such as `(+ 1 2)` produce only `[object Object]` as output. Stranger still, exceptions and explicit output using `print` work as expected.

![screenshot 2015-06-18 10 22 29](https://cloud.githubusercontent.com/assets/178038/8227035/08828072-15a4-11e5-965b-556ffb47277a.png)

Looking at the WS traffic, what's coming from the server seems correct, although potentially quoted one time too many. For instance `(+ 1 2)` results in:

```
{"id":"89fa25e5-7b0a-4c54-827b-a6c3d207224d","ns":"tranquil-galaxy","session":"1b0a16ff-5747-4d87-bb76-99f8d6226ad1","value":"{\"type\":\"html\",\"content\":\"<span class='clj-string'>&quot;3&quot;</span>\",\"value\":\"\\\"3\\\"\"}"}
```

There are no Javascript errors. OS X. Have tried in Chrome 44 and Safari.

**Comment by JonyEpsilon** [comment] 2015-06-18 10:52
That is very strange ... what version on Gorilla are you using, and what command did you start it with?

**Comment by sbelak** [comment] 2015-06-18 10:59
0.3.4 (from Clojars)
lein gorilla (from a blank project)

**Comment by JonyEpsilon** [comment] 2015-06-18 11:00
Huh. The only thing I can think of is if one of the dependencies "bundled" with Leiningen has changed - what version of lein are you using? I'll try and reproduce on a fresh VM.

**Comment by sbelak** [comment] 2015-06-18 11:05
2.51. 
I've now tried with a clean profiles.clj and it works as it should, so it must have been a conflict with one of the other plugins.

**Comment by swizzard** [comment] 2015-07-25 15:12
I just ran into this issue. I removed `cider-nrepl` and `venantius/ultra` from my `~/.lein/profiles.clj` profile, and the problem is solved. I suspect there's simply a limit to the number of things that can mess with the (n)repl without things going awry.

**Comment by JonyEpsilon** [comment] 2015-08-02 23:01
Hi Sam, thanks for the details. I think Gorilla needs to be compatible with cider, as cider is so widely used. I'll look in to this and try and figure out how to work around the problem.

**Comment by benfb** [comment] 2018-11-22 22:49
I'm going to hope this is fixed with the latest version, `org.clojars.benfb/gorilla-repl "0.5.1"`. If not, please open a new issue at benfb/gorilla-repl. Thanks!

**Closed by benfb** 2018-11-22 22:49 UTC
Labels: bug
